# python -m pytest -v -rs -s tests/test_transform_integration.py

import os
import pandas as pd
import pytest
import unicodedata
import re
from pathlib import Path

from papers_lab.io import Storage
from papers_lab.io import PaperTransform


def _collect_research_objects(base_dir: Path) -> list:
    """
    Loads research objects generated by the orchestrator (papers_test folder).
    Looks in papers_test/ieee and papers_test/acm. If not found, returns an empty list.
    """
    store = Storage()
    researches = []

    ieee_dir = base_dir / "ieee"
    if ieee_dir.exists():
        researches.extend(store.load_dir(ieee_dir, pattern="*.pkl", recursive=True))

    acm_dir = base_dir / "acm"
    if acm_dir.exists():
        researches.extend(store.load_dir(acm_dir, pattern="*.pkl", recursive=True))

    return researches


@pytest.fixture(scope="module")
def researches():
    """
    Uses the files already generated by test_papers_lab.py (default: papers_test/).
    If nothing is found, skips the tests.
    """
    base = Path("papers_test")
    objs = _collect_research_objects(base)
    if not objs:
        pytest.skip(
            "No .pkl files found in papers_test/. "
            "Run the collector (test_papers_lab.py) before these tests."
        )
    return objs


@pytest.fixture(scope="module")
def df_transformed(researches):
    """
    Executes the actual transform on the persisted objects.
    """
    tx = PaperTransform(doi_col="DOI", date_col="date", sep=".")
    df = tx.transform(
        researches,
        drop_invalid_doi=True,
        keep=None,        
        rename=None,
        schema={"year": "Int64", "month": "Int64"},
        count_cols=("keywords", "authors"),
    )
    return df

import unicodedata
import re

def _strip_accents_lower(s: str) -> str:
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = unicodedata.normalize("NFKC", s).lower().strip()
    s = re.sub(r"\s+", " ", s)
    return s

def test_basic_shape_and_columns(df_transformed: pd.DataFrame):
    """
    Basic checks on the transformed DataFrame.
    """
    assert isinstance(df_transformed, pd.DataFrame)
    for col in ("DOI", "year", "month", "year_month"):
        assert col in df_transformed.columns, f"missing column: {col}"


def test_doi_uniqueness(df_transformed: pd.DataFrame):
    """
    Ensure all DOIs are unique in the transformed DataFrame.
    """
    n_rows = len(df_transformed)
    n_unique = df_transformed["DOI"].nunique()
    assert n_rows == n_unique, f"Duplicated DOIs found: rows={n_rows}, unique={n_unique}"


def test_year_month_extraction(df_transformed: pd.DataFrame):
    """
    If 'date' column exists, 'year' and 'month' columns should exist and have valid data.
    """
    if "date" in df_transformed.columns:
        assert "year" in df_transformed.columns and "month" in df_transformed.columns
        some_year = df_transformed["year"].notna().any()
        some_month = df_transformed["month"].notna().any()
        assert some_year or some_month


def test_counts_columns_when_present(df_transformed: pd.DataFrame):
    """
    If 'keywords' or 'authors' columns exist, corresponding count columns should exist and be non-negative.
    """
    if "keywords" in df_transformed.columns:
        assert "n_keywords" in df_transformed.columns
        assert (df_transformed["n_keywords"] >= 0).all()
    if "authors" in df_transformed.columns:
        assert "n_authors" in df_transformed.columns
        assert (df_transformed["n_authors"] >= 0).all()


def test_validate_doi_format(df_transformed: pd.DataFrame):
    """
    Ensure all DOIs in the transformed DataFrame match a basic DOI format.
    """
    bad = df_transformed[~df_transformed["DOI"].astype("string").str.match(r"^10\.\S+$", na=False)]
    assert bad.empty, f"Invalid DOI format rows: {len(bad)}"

def test_keywords_normalization_presence(df_transformed: pd.DataFrame):
    """
    If 'keywords' exists, 'keywords_norm' must exist (normalization applied).
    """
    if "keywords" in df_transformed.columns:
        assert "keywords_norm" in df_transformed.columns, "missing column: keywords_norm"

def test_keywords_normalization_semantics(df_transformed: pd.DataFrame):
    """
    keywords_norm should be a list, without None, deduplicated, ordered, and normalized (lowercase/without accents).
    """
    if "keywords" not in df_transformed.columns or "keywords_norm" not in df_transformed.columns:
        return  
    
    mask = df_transformed["keywords"].apply(lambda x: isinstance(x, (list, tuple, set)) and len(x) > 0)
    if not mask.any():
        return 
    
    sample = df_transformed.loc[mask].head(10)

    for _, row in sample.iterrows():
        norm = row["keywords_norm"]
        assert isinstance(norm, list), "keywords_norm must be a list"
        assert all(k is not None for k in norm), "keywords_norm must not contain None"
        assert len(norm) == len(set(norm)), "keywords_norm must be deduplicated"
        assert norm == sorted(norm), "keywords_norm must be sorted"
        for k in norm:
            assert k == _strip_accents_lower(k), f"token not normalized: {k}"
